# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from RL_AI.protos import seaengine_pb2 as RL__AI_dot_protos_dot_seaengine__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in RL_AI/protos/seaengine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SeaEngineServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/seaengine.SeaEngineService/Ping',
                request_serializer=RL__AI_dot_protos_dot_seaengine__pb2.Empty.SerializeToString,
                response_deserializer=RL__AI_dot_protos_dot_seaengine__pb2.PongResponse.FromString,
                _registered_method=True)
        self.InitGame = channel.unary_unary(
                '/seaengine.SeaEngineService/InitGame',
                request_serializer=RL__AI_dot_protos_dot_seaengine__pb2.InitRequest.SerializeToString,
                response_deserializer=RL__AI_dot_protos_dot_seaengine__pb2.Snapshot.FromString,
                _registered_method=True)
        self.ApplyAction = channel.unary_unary(
                '/seaengine.SeaEngineService/ApplyAction',
                request_serializer=RL__AI_dot_protos_dot_seaengine__pb2.ActionRequest.SerializeToString,
                response_deserializer=RL__AI_dot_protos_dot_seaengine__pb2.Snapshot.FromString,
                _registered_method=True)
        self.GetSnapshot = channel.unary_unary(
                '/seaengine.SeaEngineService/GetSnapshot',
                request_serializer=RL__AI_dot_protos_dot_seaengine__pb2.Empty.SerializeToString,
                response_deserializer=RL__AI_dot_protos_dot_seaengine__pb2.Snapshot.FromString,
                _registered_method=True)


class SeaEngineServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SeaEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=RL__AI_dot_protos_dot_seaengine__pb2.Empty.FromString,
                    response_serializer=RL__AI_dot_protos_dot_seaengine__pb2.PongResponse.SerializeToString,
            ),
            'InitGame': grpc.unary_unary_rpc_method_handler(
                    servicer.InitGame,
                    request_deserializer=RL__AI_dot_protos_dot_seaengine__pb2.InitRequest.FromString,
                    response_serializer=RL__AI_dot_protos_dot_seaengine__pb2.Snapshot.SerializeToString,
            ),
            'ApplyAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyAction,
                    request_deserializer=RL__AI_dot_protos_dot_seaengine__pb2.ActionRequest.FromString,
                    response_serializer=RL__AI_dot_protos_dot_seaengine__pb2.Snapshot.SerializeToString,
            ),
            'GetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshot,
                    request_deserializer=RL__AI_dot_protos_dot_seaengine__pb2.Empty.FromString,
                    response_serializer=RL__AI_dot_protos_dot_seaengine__pb2.Snapshot.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'seaengine.SeaEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('seaengine.SeaEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SeaEngineService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seaengine.SeaEngineService/Ping',
            RL__AI_dot_protos_dot_seaengine__pb2.Empty.SerializeToString,
            RL__AI_dot_protos_dot_seaengine__pb2.PongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seaengine.SeaEngineService/InitGame',
            RL__AI_dot_protos_dot_seaengine__pb2.InitRequest.SerializeToString,
            RL__AI_dot_protos_dot_seaengine__pb2.Snapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seaengine.SeaEngineService/ApplyAction',
            RL__AI_dot_protos_dot_seaengine__pb2.ActionRequest.SerializeToString,
            RL__AI_dot_protos_dot_seaengine__pb2.Snapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seaengine.SeaEngineService/GetSnapshot',
            RL__AI_dot_protos_dot_seaengine__pb2.Empty.SerializeToString,
            RL__AI_dot_protos_dot_seaengine__pb2.Snapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
